.PHONY: all clean run-example run

all:

clean:

run-example:
	@./map.py -f example.txt -v
	@./map.py -f example.txt -v -g

run:
	@./map.py -f actual_input.txt -v
	@./map.py -f actual_input.txt -v -g
