.PHONY: all clean run-example run

all:

clean:

run-example:
	@./distances.escript example.txt
	@./similarity.escript example.txt

run:
	@./distances.escript actual_input.txt
	@./similarity.escript actual_input.txt
