.PHONY: all clean run-example run

all:
	@+$(MAKE) -s -C 01 all
	@+$(MAKE) -s -C 02 all
	@+$(MAKE) -s -C 03 all
	@+$(MAKE) -s -C 04 all

clean:
	@+$(MAKE) -s -C 01 clean
	@+$(MAKE) -s -C 02 clean
	@+$(MAKE) -s -C 03 clean
	@+$(MAKE) -s -C 04 clean

run-example:
	@+$(MAKE) -s -C 01 run-example
	@+$(MAKE) -s -C 02 run-example
	@+$(MAKE) -s -C 03 run-example
	@+$(MAKE) -s -C 04 run-example

run:
	@+$(MAKE) -s -C 01 run
	@+$(MAKE) -s -C 02 run
	@+$(MAKE) -s -C 03 run
	@+$(MAKE) -s -C 04 run
