.PHONY: all clean run-example run

all:
	@+$(MAKE) -s -C 01 all
	@+$(MAKE) -s -C 02 all

clean:
	@+$(MAKE) -s -C 01 clean
	@+$(MAKE) -s -C 02 clean

run-example:
	@+$(MAKE) -s -C 01 run-example
	@+$(MAKE) -s -C 02 run-example

run:
	@+$(MAKE) -s -C 01 run
	@+$(MAKE) -s -C 02 run
