.PHONY: all clean run-example run

all:

clean:

run-example:
	@clojure -M aoc2025021.clj example.txt
	@clojure -M aoc2025022.clj example.txt

run:
	@clojure -M aoc2025021.clj actual_input.txt
	@clojure -M aoc2025022.clj actual_input.txt
