.PHONY: all clean run-example run

all:

clean:

run-example:
	@clojure -M aoc2025031.clj example.txt
	@clojure -M aoc2025032.clj example.txt

run:
	@clojure -M aoc2025031.clj actual_input.txt
	@clojure -M aoc2025032.clj actual_input.txt
