.PHONY: all clean run-example run

all:

clean:

run-example:
	@./location.escript example.txt
	@./location-ranges.escript example.txt

run:
	@./location.escript actual_input.txt
	@./location-ranges.escript actual_input.txt
