.PHONY: all clean run-example run

all:

clean:

run-example:
	@./recover.pl example_1.txt
	@./recover_corrected.pl example_1.txt

run:
	@./recover.pl actual_input.txt
	@./recover_corrected.pl actual_input.txt
