.PHONY: all clean run-example run

all:

clean:

run-example:
	@clojure -M aoc2025011.clj example.txt
	@clojure -M aoc2025012.clj example.txt

run:
	@clojure -M aoc2025011.clj actual_input.txt
	@clojure -M aoc2025012.clj actual_input.txt
